const INVESTMENT_DETAILS = {
  PORTFOLIO_NAME: {
    LABEL: 'Portfolio Name',
    PLACEHOLDER: 'Enter Portfolio Name',
    ID: 'portfolioName',
    NAME: 'portfolioName',
    TYPE: 'text',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  PORTFOLIO_TYPE: {
    LABEL: 'Portfolio Type',
    OPTIONS: ['Income', 'Growth', 'Value', 'Speculative', 'Aggressive'],
    VALUES: ['', 'Income', 'Growth', 'Value', 'Speculative', 'Aggressive'],
    ID: 'portfolioType',
    NAME: 'portfolioType',
    TYPE: 'radio',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: true,
  },
  INVESTMENT_GOAL: {
    LABEL: 'Investment Goal',
    OPTIONS: [
      '-- Select --',
      'Income Generation',
      'Capital Preservation',
      'Tax Saving',
      'Diversification',
      'Beating Inflation',
      'Risk Management',
      'Capital Appreciation',
    ],
    VALUES: [
      '',
      'Income Generation',
      'Capital Preservation',
      'Tax Saving',
      'Diversification',
      'Beating Inflation',
      'Risk Management',
      'Capital Appreciation',
    ],
    ID: 'investmentGoal',
    NAME: 'investmentGoal',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  INVESTMENT_HORIZON: {
    LABEL: 'Investment Horizon',
    OPTIONS: [
      '-- Select --',
      'Short-Term Investment Horizon',
      'Medium-Term Investment Horizon',
      'Long-Term Investment Horizon',
    ],
    VALUES: [
      '',
      'Short-Term Investment Horizon',
      'Medium-Term Investment Horizon',
      'Long-Term Investment Horizon',
    ],
    ID: 'investmentHorizon',
    NAME: 'investmentHorizon',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  RISK_TOLERANCE: {
    LABEL: 'Risk Tolerance',
    OPTIONS: ['Aggressive', 'Moderate', 'Considerate', 'Flexible', 'Adjustable'],
    ID: 'riskTolerance',
    NAME: 'riskTolerance',
    TYPE: 'radio',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: true,
  },
};

const ASSET_ALLOCATION = {
  ANNUAL_INVESTMENT_CAPACITY: {
    LABEL: 'Annual Investment Capacity',
    // PLACEHOLDER: 'Enter a amount, greater than 1',
    PLACEHOLDER: 'INR',
    ID: 'annualInvestmentCapacity',
    NAME: 'annualInvestmentCapacity',
    TYPE: 'text',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  CURRENCY: {
    OPTIONS: ['₹', '$'],
    ID: 'curreny',
    VALUE: ['INR', 'Dollar'],
    NAME: 'curreny',
    REQUIRED: false,
  },
  LUMP_SUM_AMOUNT: {
    LABEL: 'Lump Sum Amount',
    PLACEHOLDER: 'INR',
    TYPE: 'number',
    ID: 'lumpSumAmount',
    NAME: 'lumpSumAmount',
    CLASS: ['fieldTitle'],
    REQUIRED: false,
  },
  MONTHLY_CONTRIBUTION: {
    LABEL: 'Monthly Contribution',
    PLACEHOLDER: 'INR',
    TYPE: 'number',
    ID: 'monthlyContribution',
    NAME: 'monthlyContribution',
    CLASS: ['fieldTitle'],
    REQUIRED: false,
  },
  ASSETS: {
    TITLE: 'Assets',
    CLASS: ['fieldTitle'],
  },
  ASSET_CLASS: {
    LABEL: 'Asset Class',
    OPTIONS: ['-- Select --', 'Stock', 'Bond', 'Cash', 'Real Estate', 'Forex'],
    VALUES: ['', 'Equity', 'Fixed Income', 'Cash Equivalent', 'REITs', 'Foreign Exchange'],
    ID: 'assetClass',
    NAME: 'assetClass',
    CLASS: ['subFieldTitle'],
    REQUIRED: true,
  },
  PERCENTAGE_ALLOCATION: {
    LABEL: 'Percentage Allocation(%)',
    TYPE: 'number',
    ID: 'percentageAllocation',
    NAME: 'percentageAllocation',
    CLASS: ['subFieldTitle'],
    REQUIRED: true,
  },
  SPECIFIC_FUND: {
    LABEL: 'Specific Fund',
    TYPE: 'text',
    ID: 'specificFund',
    NAME: 'specificFund',
    CLASS: ['subFieldTitle'],
    REQUIRED: false,
  },
  CURRENT_VALUE: {
    LABEL: 'Current Value',
    PLACEHOLDER: 'INR',
    TYPE: 'number',
    ID: 'currentValue',
    NAME: 'currentValue',
    CLASS: ['subFieldTitle'],
    REQUIRED: false,
  },
  ADD_ASSET: {
    LABEL: 'Add Asset +',
    ID: 'addAssetButton',
  },
  INVESTMENT_STYLE: {
    LABEL: 'Investment Style',
    OPTIONS: ['Large', 'Medium', 'Small'],
    ID: 'investmentStyle',
    NAME: 'investmentStyle',
    TYPE: 'checkbox',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: false,
  },
};

const PREFERENCES = {
  AUTOMATED_REBALANCING: {
    LABEL: 'Opt for Automated Rebalancing?',
    OPTIONS: ['Yes', 'No'],
    ID: 'automatedRebalancing',
    NAME: 'automatedRebalancing',
    TYPE: 'radio',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: true,
  },
  TAX_SAVING_PREF: {
    LABEL: 'Tax Saving Preference',
    OPTIONS: ['Yes', 'No'],
    ID: 'taxSavingPreference',
    NAME: 'taxSavingPreference',
    TYPE: 'radio',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: false,
  },
  FINANCIAL_GOALS: {
    LABEL: 'Future Finalcial Goals',
    PLACEHOLDER: 'Describe Briefly',
    ID: 'financialGoal',
    NAME: 'financialGoal',
    ROWS: 12,
    CLASS: ['fieldTitle'],
    REQUIRED: false,
  },
  RISK_ACKNOWLEDGEMENT: {
    LABEL: 'Risk Acknowledgement',
    OPTIONS: [''],
    ID: 'riskAcknowledgement',
    NAME: 'riskAcknowledgement',
    TYPE: 'checkbox',
    TEXT_CONTENT:
      'All investments are subject to market risks. Please read all scheme-related documents carefully before investing.',
    HIDDEN: false,
    CLASS: [''],
    REQUIRED: true,
  },
};

const NAVIGATION = {
  PREVIOUS: {
    LABEL: 'Previous',
    ID: 'previousButton',
  },
  CONTINUE: {
    LABEL: 'Continue',
    ID: 'continueButton',
  },
  SUBMIT: {
    LABEL: 'Submit',
    ID: 'submitButton',
  },
};

const TABLE = {
  HEADERS: [
    'Portfolio Name',
    'Portfolio Type',
    'Investment Goal',
    'Investment Horizon',
    'Risk Tolerance',
    'Annual Investment',
    'Assets',
    'Automated Rebalancing',
  ],
  KEYS: [
    'portfolioName',
    'portfolioType',
    'investmentGoal',
    'investmentHorizon',
    'riskTolerance',
    'annualInvestmentCapacity',
    'assets',
    'automatedRebalancing',
  ],
};

export { INVESTMENT_DETAILS, ASSET_ALLOCATION, PREFERENCES, NAVIGATION, TABLE };
