export const ASSET_ALLOCATION = {
  ANNUAL_INVESTMENT_CAPACITY: {
    LABEL: 'Annual Investment Capacity',
    // PLACEHOLDER: 'Enter a amount, greater than 1',
    PLACEHOLDER: 'INR',
    ID: 'annualInvestmentCapacity',
    NAME: 'annualInvestmentCapacity',
    TYPE: 'text',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  CURRENCY: {
    OPTIONS: ['₹', '$'],
    ID: 'currency',
    VALUE: ['INR', 'USD'],
    NAME: 'currency',
    REQUIRED: false,
  },
  LUMP_SUM_AMOUNT: {
    LABEL: 'Lump Sum Amount',
    PLACEHOLDER: 'INR',
    TYPE: 'number',
    ID: 'lumpSumAmount',
    NAME: 'lumpSumAmount',
    CLASS: ['fieldTitle'],
    REQUIRED: false,
  },
  MONTHLY_CONTRIBUTION: {
    LABEL: 'Monthly Contribution',
    PLACEHOLDER: 'INR',
    TYPE: 'number',
    ID: 'monthlyContribution',
    NAME: 'monthlyContribution',
    CLASS: ['fieldTitle'],
    REQUIRED: false,
  },
  ASSETS: {
    TITLE: 'Assets',
    CLASS: ['fieldTitle'],
  },
  ASSET_CLASS: {
    LABEL: 'Asset Class',
    OPTIONS: ['-- Select --', 'Stock', 'Bond', 'Cash', 'Real Estate', 'Forex'],
    VALUES: ['', 'Equity', 'Fixed Income', 'Cash Equivalent', 'REITs', 'Foreign Exchange'],
    ID: 'assetClass',
    NAME: 'assetClass',
    CLASS: ['subFieldTitle'],
    REQUIRED: true,
  },
  PERCENTAGE_ALLOCATION: {
    LABEL: 'Percentage Allocation(%)',
    TYPE: 'number',
    ID: 'percentageAllocation',
    NAME: 'percentageAllocation',
    CLASS: ['subFieldTitle'],
    REQUIRED: true,
  },
  SPECIFIC_FUND: {
    LABEL: 'Specific Fund',
    TYPE: 'text',
    ID: 'specificFund',
    NAME: 'specificFund',
    CLASS: ['subFieldTitle'],
    REQUIRED: false,
  },
  CURRENT_VALUE: {
    LABEL: 'Current Value',
    PLACEHOLDER: 'INR',
    TYPE: 'number',
    ID: 'currentValue',
    NAME: 'currentValue',
    CLASS: ['subFieldTitle'],
    REQUIRED: false,
  },
  ADD_ASSET: {
    LABEL: 'Add Asset +',
    ID: 'addAssetButton',
  },
  INVESTMENT_STYLE: {
    LABEL: 'Investment Style',
    OPTIONS: ['Large', 'Medium', 'Small'],
    ID: 'investmentStyle',
    NAME: 'investmentStyle',
    TYPE: 'checkbox',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: false,
  },
};
