export const INVESTMENT_DETAILS = {
  PORTFOLIO_NAME: {
    LABEL: 'Portfolio Name',
    PLACEHOLDER: 'Enter Portfolio Name',
    ID: 'portfolioName',
    NAME: 'portfolioName',
    TYPE: 'text',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  PORTFOLIO_TYPE: {
    LABEL: 'Portfolio Type',
    OPTIONS: ['Income', 'Growth', 'Value', 'Speculative', 'Aggressive'],
    VALUES: ['', 'Income', 'Growth', 'Value', 'Speculative', 'Aggressive'],
    ID: 'portfolioType',
    NAME: 'portfolioType',
    TYPE: 'radio',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: true,
  },
  INVESTMENT_GOAL: {
    LABEL: 'Investment Goal',
    OPTIONS: [
      '-- Select --',
      'Income Generation',
      'Capital Preservation',
      'Tax Saving',
      'Diversification',
      'Beating Inflation',
      'Risk Management',
      'Capital Appreciation',
    ],
    VALUES: [
      '',
      'Income Generation',
      'Capital Preservation',
      'Tax Saving',
      'Diversification',
      'Beating Inflation',
      'Risk Management',
      'Capital Appreciation',
    ],
    ID: 'investmentGoal',
    NAME: 'investmentGoal',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  INVESTMENT_HORIZON: {
    LABEL: 'Investment Horizon',
    OPTIONS: [
      '-- Select --',
      'Short-Term Investment Horizon',
      'Medium-Term Investment Horizon',
      'Long-Term Investment Horizon',
    ],
    VALUES: [
      '',
      'Short-Term Investment Horizon',
      'Medium-Term Investment Horizon',
      'Long-Term Investment Horizon',
    ],
    ID: 'investmentHorizon',
    NAME: 'investmentHorizon',
    CLASS: ['fieldTitle'],
    REQUIRED: true,
  },
  RISK_TOLERANCE: {
    LABEL: 'Risk Tolerance',
    OPTIONS: ['Aggressive', 'Moderate', 'Considerate', 'Flexible', 'Adjustable'],
    ID: 'riskTolerance',
    NAME: 'riskTolerance',
    TYPE: 'radio',
    HIDDEN: true,
    CLASS: ['fieldTitle', 'radioCheckboxText'],
    REQUIRED: true,
  },
};
